### ISSUE TITLE
Exercise: Refactoring The Bad Boids

### ISSUE THREAD

**Issue by mattgillucl** [UCL/rsd-engineeringcourse#109]
1. Bad_Boids - Why is the traceback shown?

2. Bad_Boids - should we declare a bird package? In the Regression Test section following this it uses `before=deepcopy(boids.boids)` - why do we need `boids.boids` rather than just `boids`?

3. What exactly are we storing in the regression test yaml?

4. The link under "Start Refactoring" is broken.

**Comment by dpshelio** [comment]
1. should be fixed now... and a graph added for the notebook and page.
2. They are not running cells, and everything works using the repository where that's shown. We need `boids.boids` because the file that we are loading is called boids, and from there we are using the variable `boids`.
3. That a single step changes from one position to the next. So it stores all the positions and velocities before and after running. See the [content of `fixture.yml`](https://github.com/jamespjh/bad-boids/blob/master/fixture.yml)
4. fixed

@ageorgou 
1. thanks
2. Updated
3. I'm not changing that as pytest run it fine. And it's good they are exposed to it.
